---
name: test
on:
    workflow_call:

    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - name: Install modules
              run: npm install
            - name: Run ESLint
              run: npm run lint

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - name: Install modules
              run: npm install
            - name: Run build
              run: npm run build

    version-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - name: Install modules
              run: npm install
            - name: Run ESLint
              run: npm run version
